// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssoAPI.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IDRequest struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDRequest) Reset()         { *m = IDRequest{} }
func (m *IDRequest) String() string { return proto.CompactTextString(m) }
func (*IDRequest) ProtoMessage()    {}
func (*IDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3abf92a51eb40eb1, []int{0}
}

func (m *IDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDRequest.Unmarshal(m, b)
}
func (m *IDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDRequest.Marshal(b, m, deterministic)
}
func (m *IDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDRequest.Merge(m, src)
}
func (m *IDRequest) XXX_Size() int {
	return xxx_messageInfo_IDRequest.Size(m)
}
func (m *IDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IDRequest proto.InternalMessageInfo

func (m *IDRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ClientResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SecretHash           string   `protobuf:"bytes,3,opt,name=secretHash,proto3" json:"secretHash,omitempty"`
	SecretSalt           string   `protobuf:"bytes,4,opt,name=secretSalt,proto3" json:"secretSalt,omitempty"`
	RedirectUri          string   `protobuf:"bytes,5,opt,name=redirectUri,proto3" json:"redirectUri,omitempty"`
	Scopes               []*Scope `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
	Visibility           string   `protobuf:"bytes,7,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Type                 string   `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	EntityID             string   `protobuf:"bytes,9,opt,name=entityID,proto3" json:"entityID,omitempty"`
	LicenseID            uint64   `protobuf:"varint,10,opt,name=licenseID,proto3" json:"licenseID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientResponse) Reset()         { *m = ClientResponse{} }
func (m *ClientResponse) String() string { return proto.CompactTextString(m) }
func (*ClientResponse) ProtoMessage()    {}
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3abf92a51eb40eb1, []int{1}
}

func (m *ClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientResponse.Unmarshal(m, b)
}
func (m *ClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientResponse.Marshal(b, m, deterministic)
}
func (m *ClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientResponse.Merge(m, src)
}
func (m *ClientResponse) XXX_Size() int {
	return xxx_messageInfo_ClientResponse.Size(m)
}
func (m *ClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientResponse proto.InternalMessageInfo

func (m *ClientResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClientResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClientResponse) GetSecretHash() string {
	if m != nil {
		return m.SecretHash
	}
	return ""
}

func (m *ClientResponse) GetSecretSalt() string {
	if m != nil {
		return m.SecretSalt
	}
	return ""
}

func (m *ClientResponse) GetRedirectUri() string {
	if m != nil {
		return m.RedirectUri
	}
	return ""
}

func (m *ClientResponse) GetScopes() []*Scope {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *ClientResponse) GetVisibility() string {
	if m != nil {
		return m.Visibility
	}
	return ""
}

func (m *ClientResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ClientResponse) GetEntityID() string {
	if m != nil {
		return m.EntityID
	}
	return ""
}

func (m *ClientResponse) GetLicenseID() uint64 {
	if m != nil {
		return m.LicenseID
	}
	return 0
}

type Scope struct {
	Scope                string   `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Required             bool     `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Scope) Reset()         { *m = Scope{} }
func (m *Scope) String() string { return proto.CompactTextString(m) }
func (*Scope) ProtoMessage()    {}
func (*Scope) Descriptor() ([]byte, []int) {
	return fileDescriptor_3abf92a51eb40eb1, []int{2}
}

func (m *Scope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scope.Unmarshal(m, b)
}
func (m *Scope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scope.Marshal(b, m, deterministic)
}
func (m *Scope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scope.Merge(m, src)
}
func (m *Scope) XXX_Size() int {
	return xxx_messageInfo_Scope.Size(m)
}
func (m *Scope) XXX_DiscardUnknown() {
	xxx_messageInfo_Scope.DiscardUnknown(m)
}

var xxx_messageInfo_Scope proto.InternalMessageInfo

func (m *Scope) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *Scope) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

type ClientStatsResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LicensesAuthorized   uint64   `protobuf:"varint,2,opt,name=licensesAuthorized,proto3" json:"licensesAuthorized,omitempty"`
	EntitiesAuthorized   uint64   `protobuf:"varint,3,opt,name=entitiesAuthorized,proto3" json:"entitiesAuthorized,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientStatsResponse) Reset()         { *m = ClientStatsResponse{} }
func (m *ClientStatsResponse) String() string { return proto.CompactTextString(m) }
func (*ClientStatsResponse) ProtoMessage()    {}
func (*ClientStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3abf92a51eb40eb1, []int{3}
}

func (m *ClientStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientStatsResponse.Unmarshal(m, b)
}
func (m *ClientStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientStatsResponse.Marshal(b, m, deterministic)
}
func (m *ClientStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientStatsResponse.Merge(m, src)
}
func (m *ClientStatsResponse) XXX_Size() int {
	return xxx_messageInfo_ClientStatsResponse.Size(m)
}
func (m *ClientStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientStatsResponse proto.InternalMessageInfo

func (m *ClientStatsResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClientStatsResponse) GetLicensesAuthorized() uint64 {
	if m != nil {
		return m.LicensesAuthorized
	}
	return 0
}

func (m *ClientStatsResponse) GetEntitiesAuthorized() uint64 {
	if m != nil {
		return m.EntitiesAuthorized
	}
	return 0
}

type TokenInfoResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientID             string   `protobuf:"bytes,2,opt,name=clientID,proto3" json:"clientID,omitempty"`
	EntityID             string   `protobuf:"bytes,3,opt,name=entityID,proto3" json:"entityID,omitempty"`
	ExpiresIn            int32    `protobuf:"varint,4,opt,name=expiresIn,proto3" json:"expiresIn,omitempty"`
	LicenseID            uint64   `protobuf:"varint,5,opt,name=licenseID,proto3" json:"licenseID,omitempty"`
	Scope                string   `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`
	Ghost                string   `protobuf:"bytes,7,opt,name=ghost,proto3" json:"ghost,omitempty"`
	Type                 string   `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenInfoResponse) Reset()         { *m = TokenInfoResponse{} }
func (m *TokenInfoResponse) String() string { return proto.CompactTextString(m) }
func (*TokenInfoResponse) ProtoMessage()    {}
func (*TokenInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3abf92a51eb40eb1, []int{4}
}

func (m *TokenInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenInfoResponse.Unmarshal(m, b)
}
func (m *TokenInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenInfoResponse.Marshal(b, m, deterministic)
}
func (m *TokenInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenInfoResponse.Merge(m, src)
}
func (m *TokenInfoResponse) XXX_Size() int {
	return xxx_messageInfo_TokenInfoResponse.Size(m)
}
func (m *TokenInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenInfoResponse proto.InternalMessageInfo

func (m *TokenInfoResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TokenInfoResponse) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *TokenInfoResponse) GetEntityID() string {
	if m != nil {
		return m.EntityID
	}
	return ""
}

func (m *TokenInfoResponse) GetExpiresIn() int32 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *TokenInfoResponse) GetLicenseID() uint64 {
	if m != nil {
		return m.LicenseID
	}
	return 0
}

func (m *TokenInfoResponse) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *TokenInfoResponse) GetGhost() string {
	if m != nil {
		return m.Ghost
	}
	return ""
}

func (m *TokenInfoResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type AccessToken struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	ClientID             string   `protobuf:"bytes,2,opt,name=clientID,proto3" json:"clientID,omitempty"`
	AccountID            string   `protobuf:"bytes,3,opt,name=accountID,proto3" json:"accountID,omitempty"`
	ExpiresIn            int32    `protobuf:"varint,4,opt,name=expiresIn,proto3" json:"expiresIn,omitempty"`
	OrganizationID       string   `protobuf:"bytes,5,opt,name=organizationID,proto3" json:"organizationID,omitempty"`
	Scope                string   `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`
	Ghost                string   `protobuf:"bytes,7,opt,name=ghost,proto3" json:"ghost,omitempty"`
	Type                 string   `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessToken) Reset()         { *m = AccessToken{} }
func (m *AccessToken) String() string { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()    {}
func (*AccessToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_3abf92a51eb40eb1, []int{5}
}

func (m *AccessToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessToken.Unmarshal(m, b)
}
func (m *AccessToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessToken.Marshal(b, m, deterministic)
}
func (m *AccessToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessToken.Merge(m, src)
}
func (m *AccessToken) XXX_Size() int {
	return xxx_messageInfo_AccessToken.Size(m)
}
func (m *AccessToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessToken.DiscardUnknown(m)
}

var xxx_messageInfo_AccessToken proto.InternalMessageInfo

func (m *AccessToken) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AccessToken) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *AccessToken) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *AccessToken) GetExpiresIn() int32 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *AccessToken) GetOrganizationID() string {
	if m != nil {
		return m.OrganizationID
	}
	return ""
}

func (m *AccessToken) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *AccessToken) GetGhost() string {
	if m != nil {
		return m.Ghost
	}
	return ""
}

func (m *AccessToken) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Client struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RedirectURI          string   `protobuf:"bytes,3,opt,name=redirectURI,proto3" json:"redirectURI,omitempty"`
	Visibility           string   `protobuf:"bytes,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	OrganizationID       string   `protobuf:"bytes,6,opt,name=organizationID,proto3" json:"organizationID,omitempty"`
	AccountID            string   `protobuf:"bytes,7,opt,name=accountID,proto3" json:"accountID,omitempty"`
	Scopes               []*Scope `protobuf:"bytes,8,rep,name=scopes,proto3" json:"scopes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_3abf92a51eb40eb1, []int{6}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *Client) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Client) GetRedirectURI() string {
	if m != nil {
		return m.RedirectURI
	}
	return ""
}

func (m *Client) GetVisibility() string {
	if m != nil {
		return m.Visibility
	}
	return ""
}

func (m *Client) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Client) GetOrganizationID() string {
	if m != nil {
		return m.OrganizationID
	}
	return ""
}

func (m *Client) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *Client) GetScopes() []*Scope {
	if m != nil {
		return m.Scopes
	}
	return nil
}

type PersonalAccessToken struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PersonalTokenID      string   `protobuf:"bytes,2,opt,name=personalTokenID,proto3" json:"personalTokenID,omitempty"`
	Scope                string   `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	OrganizationID       string   `protobuf:"bytes,4,opt,name=organizationID,proto3" json:"organizationID,omitempty"`
	AccountID            string   `protobuf:"bytes,5,opt,name=accountID,proto3" json:"accountID,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonalAccessToken) Reset()         { *m = PersonalAccessToken{} }
func (m *PersonalAccessToken) String() string { return proto.CompactTextString(m) }
func (*PersonalAccessToken) ProtoMessage()    {}
func (*PersonalAccessToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_3abf92a51eb40eb1, []int{7}
}

func (m *PersonalAccessToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonalAccessToken.Unmarshal(m, b)
}
func (m *PersonalAccessToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonalAccessToken.Marshal(b, m, deterministic)
}
func (m *PersonalAccessToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonalAccessToken.Merge(m, src)
}
func (m *PersonalAccessToken) XXX_Size() int {
	return xxx_messageInfo_PersonalAccessToken.Size(m)
}
func (m *PersonalAccessToken) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonalAccessToken.DiscardUnknown(m)
}

var xxx_messageInfo_PersonalAccessToken proto.InternalMessageInfo

func (m *PersonalAccessToken) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PersonalAccessToken) GetPersonalTokenID() string {
	if m != nil {
		return m.PersonalTokenID
	}
	return ""
}

func (m *PersonalAccessToken) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *PersonalAccessToken) GetOrganizationID() string {
	if m != nil {
		return m.OrganizationID
	}
	return ""
}

func (m *PersonalAccessToken) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *PersonalAccessToken) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

// returns account for a given token
// requires authorization
type Account struct {
	AccountID            string   `protobuf:"bytes,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified        bool     `protobuf:"varint,4,opt,name=emailVerified,proto3" json:"emailVerified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_3abf92a51eb40eb1, []int{8}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetEmailVerified() bool {
	if m != nil {
		return m.EmailVerified
	}
	return false
}

func init() {
	proto.RegisterType((*IDRequest)(nil), "ssoproto.IDRequest")
	proto.RegisterType((*ClientResponse)(nil), "ssoproto.ClientResponse")
	proto.RegisterType((*Scope)(nil), "ssoproto.Scope")
	proto.RegisterType((*ClientStatsResponse)(nil), "ssoproto.ClientStatsResponse")
	proto.RegisterType((*TokenInfoResponse)(nil), "ssoproto.TokenInfoResponse")
	proto.RegisterType((*AccessToken)(nil), "ssoproto.AccessToken")
	proto.RegisterType((*Client)(nil), "ssoproto.Client")
	proto.RegisterType((*PersonalAccessToken)(nil), "ssoproto.PersonalAccessToken")
	proto.RegisterType((*Account)(nil), "ssoproto.Account")
}

func init() { proto.RegisterFile("ssoAPI.proto", fileDescriptor_3abf92a51eb40eb1) }

var fileDescriptor_3abf92a51eb40eb1 = []byte{
	// 727 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0x8e, 0x93, 0xd8, 0xb5, 0xa7, 0xfd, 0xd3, 0xbf, 0xdb, 0x20, 0x59, 0xa5, 0xa0, 0xb0, 0x42,
	0x90, 0x53, 0x0e, 0x45, 0x08, 0x55, 0xe2, 0x12, 0x88, 0x28, 0xe6, 0x42, 0xe4, 0x00, 0x77, 0xd7,
	0x99, 0xb6, 0x2b, 0x5c, 0x6f, 0xea, 0xdd, 0x14, 0xda, 0x3b, 0x6f, 0xc0, 0x6b, 0xf0, 0x28, 0x9c,
	0x79, 0x0c, 0x9e, 0x00, 0x09, 0x79, 0xed, 0x64, 0x6d, 0xc7, 0x69, 0x11, 0xdc, 0x76, 0xbe, 0x19,
	0xcf, 0xce, 0xf7, 0xcd, 0xcc, 0x1a, 0xb6, 0x84, 0xe0, 0xc3, 0xb1, 0x37, 0x98, 0x25, 0x5c, 0x72,
	0x62, 0x0b, 0xc1, 0xd5, 0x89, 0x3e, 0x00, 0xc7, 0x1b, 0xf9, 0x78, 0x31, 0x47, 0x21, 0x49, 0x17,
	0xcc, 0xcb, 0x20, 0x9a, 0xa3, 0x6b, 0xf4, 0x8c, 0xbe, 0xe3, 0x67, 0x06, 0xfd, 0xd6, 0x84, 0xce,
	0xcb, 0x88, 0x61, 0x2c, 0x7d, 0x14, 0x33, 0x1e, 0x0b, 0x24, 0x1d, 0x68, 0xb2, 0x69, 0x1e, 0xd5,
	0x64, 0x53, 0x42, 0xa0, 0x1d, 0x07, 0xe7, 0xe8, 0x36, 0x15, 0xa2, 0xce, 0xe4, 0x3e, 0x80, 0xc0,
	0x30, 0x41, 0xf9, 0x3a, 0x10, 0x67, 0x6e, 0x4b, 0x79, 0x0a, 0x88, 0xf6, 0x4f, 0x82, 0x48, 0xba,
	0xed, 0xa2, 0x3f, 0x45, 0x48, 0x0f, 0x36, 0x13, 0x9c, 0xb2, 0x04, 0x43, 0xf9, 0x3e, 0x61, 0xae,
	0xa9, 0x02, 0x8a, 0x10, 0x79, 0x0c, 0x96, 0x08, 0xf9, 0x0c, 0x85, 0x6b, 0xf5, 0x5a, 0xfd, 0xcd,
	0x83, 0xed, 0xc1, 0x82, 0xd6, 0x60, 0x92, 0xe2, 0x7e, 0xee, 0x4e, 0xaf, 0xba, 0x64, 0x82, 0x1d,
	0xb3, 0x88, 0xc9, 0x2b, 0x77, 0x23, 0xbb, 0x4a, 0x23, 0x69, 0xf9, 0xf2, 0x6a, 0x86, 0xae, 0x9d,
	0x95, 0x9f, 0x9e, 0xc9, 0x1e, 0xd8, 0x18, 0x4b, 0x26, 0xaf, 0xbc, 0x91, 0xeb, 0x28, 0x7c, 0x69,
	0x93, 0x7d, 0x70, 0x22, 0x16, 0x62, 0x2c, 0xd0, 0x1b, 0xb9, 0xd0, 0x33, 0xfa, 0x6d, 0x5f, 0x03,
	0xf4, 0x10, 0x4c, 0x75, 0x7d, 0x2a, 0xa7, 0x2a, 0x60, 0x21, 0xa7, 0x32, 0xd2, 0xc4, 0x09, 0x5e,
	0xcc, 0x59, 0x82, 0x53, 0xa5, 0x97, 0xed, 0x2f, 0x6d, 0xfa, 0xc5, 0x80, 0xdd, 0x4c, 0xea, 0x89,
	0x0c, 0xa4, 0x58, 0xab, 0xf7, 0x00, 0x48, 0x7e, 0x9f, 0x18, 0xce, 0xe5, 0x19, 0x4f, 0xd8, 0x75,
	0x9e, 0xad, 0xed, 0xd7, 0x78, 0xd2, 0x78, 0x55, 0x3c, 0x2b, 0xc5, 0xb7, 0xb2, 0xf8, 0x55, 0x0f,
	0xfd, 0x61, 0xc0, 0xce, 0x3b, 0xfe, 0x11, 0x63, 0x2f, 0x3e, 0xe1, 0x6b, 0xab, 0xd8, 0x03, 0x3b,
	0x54, 0xc5, 0x7a, 0xa3, 0xbc, 0xf3, 0x4b, 0xbb, 0x24, 0x5f, 0x6b, 0x55, 0x3e, 0xfc, 0x3c, 0x63,
	0x09, 0x0a, 0x2f, 0x56, 0x8d, 0x37, 0x7d, 0x0d, 0x94, 0xc5, 0x35, 0x2b, 0xe2, 0x6a, 0x4d, 0xad,
	0xa2, 0xa6, 0x5d, 0x30, 0x4f, 0xcf, 0xb8, 0x90, 0x79, 0x6f, 0x33, 0xa3, 0xae, 0xad, 0xf4, 0xa7,
	0x01, 0x9b, 0xc3, 0x30, 0x44, 0x21, 0x14, 0xbf, 0x74, 0xca, 0x02, 0x6d, 0xe6, 0xe4, 0x8a, 0xd0,
	0x8d, 0x2c, 0xf7, 0xc1, 0x09, 0xc2, 0x90, 0xcf, 0x95, 0x33, 0xa3, 0xa9, 0x81, 0x5b, 0x78, 0x3e,
	0x82, 0x0e, 0x4f, 0x4e, 0x83, 0x98, 0x5d, 0x07, 0x92, 0xf1, 0x38, 0x27, 0xeb, 0xf8, 0x15, 0xf4,
	0x9f, 0x19, 0xff, 0x32, 0xc0, 0xca, 0x66, 0xaa, 0x44, 0xc5, 0xa8, 0x50, 0xa9, 0x5b, 0xe1, 0xe2,
	0x0a, 0xfa, 0x5e, 0x4e, 0xb0, 0x08, 0x55, 0x36, 0xab, 0xbd, 0x76, 0xb3, 0xcc, 0xc2, 0x66, 0xad,
	0x12, 0xb7, 0x6a, 0x89, 0x97, 0xc4, 0xdd, 0xa8, 0x8a, 0xab, 0x97, 0xdf, 0xbe, 0x71, 0xf9, 0xe9,
	0x77, 0x03, 0x76, 0xc7, 0x98, 0x08, 0x1e, 0x07, 0x51, 0xb1, 0xf3, 0x0b, 0xc2, 0x46, 0x81, 0x70,
	0x1f, 0xb6, 0x67, 0x79, 0x68, 0x36, 0xfe, 0x8b, 0x96, 0x57, 0x61, 0xdd, 0x95, 0x56, 0xb1, 0x2b,
	0xab, 0xd4, 0xda, 0xb7, 0x53, 0x33, 0x6b, 0xe6, 0x26, 0x4c, 0x30, 0x90, 0x38, 0x1d, 0xca, 0x5c,
	0x1b, 0x0d, 0xd0, 0x4f, 0xb0, 0x31, 0xcc, 0x42, 0xcb, 0x69, 0x8c, 0x6a, 0x9a, 0xba, 0x8e, 0x76,
	0xc1, 0xc4, 0xf3, 0x80, 0x45, 0x8b, 0xb2, 0x95, 0x41, 0x1e, 0xc2, 0x7f, 0xea, 0xf0, 0x01, 0x13,
	0x76, 0xc2, 0x70, 0xaa, 0xaa, 0xb6, 0xfd, 0x32, 0x78, 0xf0, 0xb5, 0x0d, 0xd6, 0x64, 0xf2, 0x76,
	0x38, 0xf6, 0xc8, 0x73, 0x70, 0x8e, 0x50, 0xe6, 0x53, 0xb5, 0xab, 0x95, 0x5f, 0xfe, 0x4a, 0xf6,
	0x5c, 0x0d, 0x96, 0xff, 0x1d, 0xb4, 0x41, 0x5e, 0x41, 0x67, 0xf9, 0xb5, 0x7a, 0xe7, 0xea, 0x53,
	0xdc, 0xab, 0xa6, 0x28, 0xbd, 0x89, 0xb4, 0x41, 0x5e, 0xc0, 0xd6, 0x11, 0xca, 0xe5, 0x3b, 0x55,
	0x9f, 0xe5, 0xae, 0x06, 0x57, 0x5e, 0x34, 0xda, 0x20, 0x6f, 0xa0, 0x7b, 0x84, 0x72, 0x5c, 0xea,
	0xee, 0xdf, 0xe6, 0x3a, 0x04, 0xe7, 0x96, 0x04, 0x77, 0x34, 0x58, 0x18, 0x45, 0xda, 0x20, 0x4f,
	0x01, 0x32, 0x8e, 0xeb, 0xbf, 0xfd, 0xbf, 0x2a, 0x07, 0x6d, 0x10, 0x0f, 0x76, 0xfe, 0xb0, 0xf4,
	0x82, 0x98, 0x35, 0xcb, 0x40, 0x1b, 0xe4, 0x99, 0x7a, 0x17, 0xd5, 0xe8, 0xac, 0x4d, 0xb2, 0x53,
	0x2a, 0x3f, 0x8d, 0xa5, 0x8d, 0x63, 0x4b, 0x01, 0x4f, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xa5,
	0x51, 0x0c, 0xea, 0x62, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SSOAPIClient is the client API for SSOAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SSOAPIClient interface {
	// deprecated
	GetClient(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*ClientResponse, error)
	GetClientStats(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*ClientStatsResponse, error)
	GetTokenInfo(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*TokenInfoResponse, error)
	GetPersonalTokenInfo(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*TokenInfoResponse, error)
	// V2
	TokenInfo(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*AccessToken, error)
	ClientInfo(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*Client, error)
	PersonalTokenInfo(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*PersonalAccessToken, error)
	AccountInfo(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*Account, error)
}

type sSOAPIClient struct {
	cc *grpc.ClientConn
}

func NewSSOAPIClient(cc *grpc.ClientConn) SSOAPIClient {
	return &sSOAPIClient{cc}
}

func (c *sSOAPIClient) GetClient(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*ClientResponse, error) {
	out := new(ClientResponse)
	err := c.cc.Invoke(ctx, "/ssoproto.SSOAPI/GetClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSOAPIClient) GetClientStats(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*ClientStatsResponse, error) {
	out := new(ClientStatsResponse)
	err := c.cc.Invoke(ctx, "/ssoproto.SSOAPI/GetClientStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSOAPIClient) GetTokenInfo(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*TokenInfoResponse, error) {
	out := new(TokenInfoResponse)
	err := c.cc.Invoke(ctx, "/ssoproto.SSOAPI/GetTokenInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSOAPIClient) GetPersonalTokenInfo(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*TokenInfoResponse, error) {
	out := new(TokenInfoResponse)
	err := c.cc.Invoke(ctx, "/ssoproto.SSOAPI/GetPersonalTokenInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSOAPIClient) TokenInfo(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*AccessToken, error) {
	out := new(AccessToken)
	err := c.cc.Invoke(ctx, "/ssoproto.SSOAPI/TokenInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSOAPIClient) ClientInfo(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*Client, error) {
	out := new(Client)
	err := c.cc.Invoke(ctx, "/ssoproto.SSOAPI/ClientInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSOAPIClient) PersonalTokenInfo(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*PersonalAccessToken, error) {
	out := new(PersonalAccessToken)
	err := c.cc.Invoke(ctx, "/ssoproto.SSOAPI/PersonalTokenInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSOAPIClient) AccountInfo(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/ssoproto.SSOAPI/AccountInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SSOAPIServer is the server API for SSOAPI service.
type SSOAPIServer interface {
	// deprecated
	GetClient(context.Context, *IDRequest) (*ClientResponse, error)
	GetClientStats(context.Context, *IDRequest) (*ClientStatsResponse, error)
	GetTokenInfo(context.Context, *IDRequest) (*TokenInfoResponse, error)
	GetPersonalTokenInfo(context.Context, *IDRequest) (*TokenInfoResponse, error)
	// V2
	TokenInfo(context.Context, *IDRequest) (*AccessToken, error)
	ClientInfo(context.Context, *IDRequest) (*Client, error)
	PersonalTokenInfo(context.Context, *IDRequest) (*PersonalAccessToken, error)
	AccountInfo(context.Context, *IDRequest) (*Account, error)
}

// UnimplementedSSOAPIServer can be embedded to have forward compatible implementations.
type UnimplementedSSOAPIServer struct {
}

func (*UnimplementedSSOAPIServer) GetClient(ctx context.Context, req *IDRequest) (*ClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClient not implemented")
}
func (*UnimplementedSSOAPIServer) GetClientStats(ctx context.Context, req *IDRequest) (*ClientStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientStats not implemented")
}
func (*UnimplementedSSOAPIServer) GetTokenInfo(ctx context.Context, req *IDRequest) (*TokenInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenInfo not implemented")
}
func (*UnimplementedSSOAPIServer) GetPersonalTokenInfo(ctx context.Context, req *IDRequest) (*TokenInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPersonalTokenInfo not implemented")
}
func (*UnimplementedSSOAPIServer) TokenInfo(ctx context.Context, req *IDRequest) (*AccessToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenInfo not implemented")
}
func (*UnimplementedSSOAPIServer) ClientInfo(ctx context.Context, req *IDRequest) (*Client, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientInfo not implemented")
}
func (*UnimplementedSSOAPIServer) PersonalTokenInfo(ctx context.Context, req *IDRequest) (*PersonalAccessToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PersonalTokenInfo not implemented")
}
func (*UnimplementedSSOAPIServer) AccountInfo(ctx context.Context, req *IDRequest) (*Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountInfo not implemented")
}

func RegisterSSOAPIServer(s *grpc.Server, srv SSOAPIServer) {
	s.RegisterService(&_SSOAPI_serviceDesc, srv)
}

func _SSOAPI_GetClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSOAPIServer).GetClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssoproto.SSOAPI/GetClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSOAPIServer).GetClient(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSOAPI_GetClientStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSOAPIServer).GetClientStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssoproto.SSOAPI/GetClientStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSOAPIServer).GetClientStats(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSOAPI_GetTokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSOAPIServer).GetTokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssoproto.SSOAPI/GetTokenInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSOAPIServer).GetTokenInfo(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSOAPI_GetPersonalTokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSOAPIServer).GetPersonalTokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssoproto.SSOAPI/GetPersonalTokenInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSOAPIServer).GetPersonalTokenInfo(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSOAPI_TokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSOAPIServer).TokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssoproto.SSOAPI/TokenInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSOAPIServer).TokenInfo(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSOAPI_ClientInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSOAPIServer).ClientInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssoproto.SSOAPI/ClientInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSOAPIServer).ClientInfo(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSOAPI_PersonalTokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSOAPIServer).PersonalTokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssoproto.SSOAPI/PersonalTokenInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSOAPIServer).PersonalTokenInfo(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSOAPI_AccountInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSOAPIServer).AccountInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssoproto.SSOAPI/AccountInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSOAPIServer).AccountInfo(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SSOAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ssoproto.SSOAPI",
	HandlerType: (*SSOAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClient",
			Handler:    _SSOAPI_GetClient_Handler,
		},
		{
			MethodName: "GetClientStats",
			Handler:    _SSOAPI_GetClientStats_Handler,
		},
		{
			MethodName: "GetTokenInfo",
			Handler:    _SSOAPI_GetTokenInfo_Handler,
		},
		{
			MethodName: "GetPersonalTokenInfo",
			Handler:    _SSOAPI_GetPersonalTokenInfo_Handler,
		},
		{
			MethodName: "TokenInfo",
			Handler:    _SSOAPI_TokenInfo_Handler,
		},
		{
			MethodName: "ClientInfo",
			Handler:    _SSOAPI_ClientInfo_Handler,
		},
		{
			MethodName: "PersonalTokenInfo",
			Handler:    _SSOAPI_PersonalTokenInfo_Handler,
		},
		{
			MethodName: "AccountInfo",
			Handler:    _SSOAPI_AccountInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ssoAPI.proto",
}
